require:
  - rubocop-performance
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  SuggestExtensions: false

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/CaseIndentation:
  IndentOneStep: true

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: no

Layout/EmptyLineAfterGuardClause:
  Enabled: no

Layout/LineLength:
  Enabled: no

Lint/SuppressedException:
  Enabled: no
  AllowComments: true

Lint/UselessAccessModifier:
  Enabled: no

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/AccessModifierDeclarations:
  Enabled: no

Style/RedundantBegin:
  Enabled: no

Style/RedundantReturn:
  Enabled: no

Style/RedundantParentheses:
  Enabled: no

Style/RescueStandardError:
  Enabled: yes
  EnforcedStyle: explicit

Style/SymbolArray:
  Enabled: yes
  EnforcedStyle: brackets

Style/RedundantInterpolation:
  Enabled: no

Style/WordArray:
  Enabled: yes
  EnforcedStyle: brackets

Metrics:
  Enabled: no

Performance/RedundantMerge:
  Enabled: no

Naming/FileName:
  Regex: !ruby/regexp /^[0-9a-z][-_0-9a-z]+$/

Lint/Void:
  CheckForMethodsWithNoSideEffects: true

Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: no

Minitest/MultipleAssertions:
  Enabled: no

Minitest/TestMethodName:
  Enabled: no

Minitest/TestFileName:
  Enabled: no
