site_name: MidiSmtpServer

site_description: "The highly customizable ruby SMTP-Service library."

copyright: "Copyright &copy; 2014 - 2023 Tom Freudenberg, 4commerce technologies AG"

docs_dir: mkdocs

nav:
  - Home: index.md
  - Installation: installation.md
  - Basic usage: basic_usage.md
  - Instantiate: instantiate.md
  - Events:
    - Overview: events.md
    - Using events: using_events.md
    - Context values: context_values.md
  - Features:
    - Load Balancing: feature_load_balancing.md
    - Authentication: feature_authentication.md
    - Encryption: feature_encryption.md
    - CR LF Modes: feature_cr_lf_modes.md
    - Internationalization: feature_8bitmime_smtputf8.md
    - Logging: feature_logging.md
    - Proxy: feature_proxy.md
  - Cookbook:
    - Recipes: cookbook.md
    - Slack MTA: cookbook_recipe_slack_mta.md
    - HAProxy load-balancing: cookbook_recipe_haproxy_mta.md
  - Support: support.md
  - Appendix:
    - Security: appendix_security.md
    - Upgrade: appendix_upgrade.md

extra_css:
  - css/extra.css

repo_url: https://github.com/4commerce-technologies-AG/midi-smtp-server

edit_uri: ""

markdown_extensions:
  - admonition

theme:
  name: readthedocs
  prev_next_buttons_location: none
  navigation_depth: 3
  sticky_navigation: false
